In [50]:
import pandas as pd
import unicodedata

In [51]:
data = pd.read_excel("../data/raw/DATOS_TEC.xlsx", sheet_name='Sheet1', index_col='Unnamed: 0')
data.head()

,CodigoProducto,Familia,Aceite_Base,Carga_Timken_Ok_lb,Corrosión_al_Cobre,Desgaste_Cuatro_Bolas_mm,Espesante,Estabilidad_Mecánica_%,Factor_de_Velocidad,Grado_ISO_VG,...,TAN_MG_KOH_G_Estandar,Viscosidad_100_C_Estandar,Viscosidad_40_C_Estandar,Color_Visual_Valor,Deteccion_de_Grumo_Valor,Extrema_Presion_Valor,Grado_ISO_VG_Valor,Grado_NLGI_Valor,Inspeccion_Visual_Valor,Textura_Valor
1,Producto_1,Grasa,Ester,60,NaN,0.5,Bentonita,NaN,NaN,NaN,...,NaN,NaN,NaN,Negro Estandar,Sin Grumo,>= 600 kg,NaN,NaN,NaN,NaN
2,Producto_2,Grasa,Mineral,60,NaN,0.3,Complejo Sulfonato de Calcio,1.2,150000.0,NaN,...,NaN,NaN,NaN,Café Estandar,Sin Grumo,NaN,NaN,1.0,NaN,Suave
3,Producto_3,Aceite,Semi-Sintetico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Negro Estandar,NaN,NaN,NaN,NaN,Cristalino,NaN
4,Producto_4,Aceite,Semi-Sintetico,NaN,NaN,NaN,NaN,NaN,NaN,32.0,...,0.5,0.0,32.0,NaN,NaN,NaN,32.0,NaN,Cristalino,NaN
5,Producto_5,Grasa,Mineral,50,1a,0.48,Poliurea,6.5,200000.0,NaN,...,NaN,NaN,NaN,Beige Estandar,Sin Grumo,>= 500 kg,NaN,NaN,NaN,Suave

In [52]:
data.info()

<class 'pandas.DataFrame'>
Index: 341 entries, 1 to 355
Data columns (total 76 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   CodigoProducto                           341 non-null    str
 1   Familia                                  341 non-null    str
 2   Aceite_Base                              341 non-null    str
 3   Carga_Timken_Ok_lb                       225 non-null    str
 4   Corrosión_al_Cobre                       115 non-null    str
 5   Desgaste_Cuatro_Bolas_mm                 158 non-null    str
 6   Espesante                                224 non-null    str
 7   Estabilidad_Mecánica_%                   179 non-null    str
 8   Factor_de_Velocidad                      158 non-null    float64
 9   Grado_ISO_VG                             97 non-null     float64
 10  Grado_NLGI_Consistencia                  224 non-null    float64
 11  Indice_de_Viscosidad                     95 non-null     str
 12  Penetración_de_Cono_a_25°C_0.1mm         225 non-null    str
 13  Peso_Específico                          69 non-null     str
 14  Punto_de_Congelamiento_°C                91 non-null     float64
 15  Punto_de_Flama_°C                        111 non-null    str
 16  Punto_de_Gota_°C                         214 non-null    str
 17  Punto_de_Soldadura_Cuatro_Bolas_kgf      239 non-null    str
 18  Registro_NSF                             72 non-null     float64
 19  Resistencia_al_Lavado_por_Agua_a_80°C_%  159 non-null    str
 20  Temperatura_de_Servicio_°C_max           252 non-null    float64
 21  Temperatura_de_Servicio_°C_min           252 non-null    float64
 22  Viscosidad_a_100°C_cSt                   95 non-null     float64
 23  Viscosidad_a_40°C_cSt                    113 non-null    str
 24  Viscosidad_del_Aceite_Base_a_40°C._cSt   219 non-null    str
 25  Color                                    324 non-null    str
 26  Textura                                  228 non-null    str
 27  Color_Numerico_Min                       88 non-null     float64
 28  Estabilidad_Mecanica_Min                 165 non-null    float64
 29  Indice_de_Viscosidad_Min                 94 non-null     float64
 30  Lavado_por_Agua_Min                      115 non-null    float64
 31  Penetracion_1_10_Min                     216 non-null    float64
 32  Penetracion_a_10_000_Min                 163 non-null    float64
 33  Penetracion_a_60_Min                     176 non-null    float64
 34  Peso_Especifico_Min                      107 non-null    float64
 35  Punto_de_Flama_Min                       88 non-null     float64
 36  Punto_de_Gota_Min                        198 non-null    float64
 37  Punto_de_Ignicion_Min                    79 non-null     float64
 38  TAN_MG_KOH_G_Min                         88 non-null     float64
 39  Viscosidad_100_C_Min                     94 non-null     float64
 40  Viscosidad_40_C_Min                      101 non-null    float64
 41  Color_Numerico_Max                       88 non-null     float64
 42  Estabilidad_Mecanica_Max                 165 non-null    float64
 43  Indice_de_Viscosidad_Max                 94 non-null     float64
 44  Lavado_por_Agua_Max                      115 non-null    float64
 45  Penetracion_1_10_Max                     216 non-null    float64
 46  Penetracion_a_10_000_Max                 163 non-null    float64
 47  Penetracion_a_60_Max                     176 non-null    float64
 48  Peso_Especifico_Max                      107 non-null    float64
 49  Punto_de_Flama_Max                       88 non-null     float64
 50  Punto_de_Gota_Max                        198 non-null    float64
 51  Punto_de_Ignicion_Max                    79 non-null     float64
 52  TAN_MG_KOH_G_Max                         88 non-null     float64
 53  Viscosidad_100_C_Max                     94 non-null     float64
 54  Viscosidad_40_C_Max                      101 non-null    float64
 55  Color_Numerico_Estandar                  88 non-null     float64
 56  Estabilidad_Mecanica_Estandar            165 non-null    float64
 57  Indice_de_Viscosidad_Estandar            94 non-null     float64
 58  Lavado_por_Agua_Estandar                 115 non-null    float64
 59  Penetracion_1_10_Estandar                216 non-null    float64
 60  Penetracion_a_10_000_Estandar            163 non-null    float64
 61  Penetracion_a_60_Estandar                176 non-null    float64
 62  Peso_Especifico_Estandar                 107 non-null    float64
 63  Punto_de_Flama_Estandar                  88 non-null     float64
 64  Punto_de_Gota_Estandar                   198 non-null    float64
 65  Punto_de_Ignicion_Estandar               79 non-null     float64
 66  TAN_MG_KOH_G_Estandar                    88 non-null     float64
 67  Viscosidad_100_C_Estandar                94 non-null     float64
 68  Viscosidad_40_C_Estandar                 101 non-null    float64
 69  Color_Visual_Valor                       233 non-null    str
 70  Deteccion_de_Grumo_Valor                 207 non-null    str
 71  Extrema_Presion_Valor                    70 non-null     str
 72  Grado_ISO_VG_Valor                       79 non-null     float64
 73  Grado_NLGI_Valor                         145 non-null    float64
 74  Inspeccion_Visual_Valor                  80 non-null     str
 75  Textura_Valor                            207 non-null    str
dtypes: float64(52), str(24)
memory usage: 205.1 KB

In [59]:
cols = data.columns

def clean_text(text):
    text = '_'.join([elem for elem in text.lower().strip().split(' ') if '/' not in elem])
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode()
    
    return text
    
cols = [clean_text(c) for c in cols]
data.columns = cols
data = data[data.columns[:26]].reset_index()
aceites_cols = list(data.columns[2:14]) + list(data.columns[15:])
display(aceites_cols)

['familia',
 'aceite_base',
 'carga_timken_ok_lb',
 'corrosion_al_cobre',
 'desgaste_cuatro_bolas_mm',
 'espesante',
 'estabilidad_mecanica_%',
 'factor_de_velocidad',
 'grado_iso_vg',
 'grado_nlgi_consistencia',
 'indice_de_viscosidad',
 'penetracion_de_cono_a_25c_0.1mm',
 'punto_de_congelamiento_c',
 'punto_de_flama_c',
 'punto_de_gota_c',
 'punto_de_soldadura_cuatro_bolas_kgf',
 'registro_nsf',
 'resistencia_al_lavado_por_agua_a_80c_%',
 'temperatura_de_servicio_c_max',
 'temperatura_de_servicio_c_min',
 'viscosidad_a_100c_cst',
 'viscosidad_a_40c_cst',
 'viscosidad_del_aceite_base_a_40c._cst',
 'color']

In [54]:
data.groupby('familia').apply(lambda x: x.isna().sum()/len(x) * 100)

,codigoproducto,aceite_base,carga_timken_ok_lb,corrosion_al_cobre,desgaste_cuatro_bolas_mm,espesante,estabilidad_mecanica_%,factor_de_velocidad,grado_iso_vg,grado_nlgi_consistencia,...,punto_de_gota_c,punto_de_soldadura_cuatro_bolas_kgf,registro_nsf,resistencia_al_lavado_por_agua_a_80c_%,temperatura_de_servicio_c_max,temperatura_de_servicio_c_min,viscosidad_a_100c_cst,viscosidad_a_40c_cst,viscosidad_del_aceite_base_a_40c._cst,color
familia,,,,,,,,,,,,,,,,,,,,,
Aceite,0.0,0.0,82.051282,59.829060,59.829060,100.0,100.000000,100.000000,17.094017,100.0,...,100.000000,82.051282,59.829060,100.000000,69.230769,69.230769,18.803419,3.418803,100.000000,12.820513
Grasa,0.0,0.0,8.928571,69.642857,50.446429,0.0,20.089286,29.464286,100.000000,0.0,...,4.464286,2.678571,88.839286,29.017857,3.571429,3.571429,100.000000,100.000000,2.232143,0.892857